### ISSUE TITLE
ライセンスの確認

### ISSUE THREAD

**Issue by Foo-x** [yto/kiseppe#3]
素敵な拡張機能をありがとうございます。
キンセリのサイトと合わせて便利に使わせていただいております。

1点質問させてください。
こちらのリポジトリのライセンスは何になるでしょうか？
forkして機能を追加しようとしているのですが、それが可能なライセンスなのか確認させていただきたいです。
よろしくお願いいたします。

**Comment by yto** [comment]
ありがとうございます。
確かにライセンスの設定がしていなかったですね。
MIT ライセンスに設定しました。

なお、kiseppe で使っている API についてはまた別の話となります。
現在は誰でもどこからでも叩ける設定になっていますが、近いうちに何かしらの規約・制限を設けるつもりです。

価格グラフ描画のAPI（KS_IF_API）（iframe用のHTMLを取得するAPI）は、キンセリへの誘導も兼ねており多用されても問題ないのです。
が、セール判定用のAPI（KS_JD_API）はそれだけ単体で使われるとサーバ負荷だけかかってこちらとしては嬉しみがないのです。
ということで、何かしらの利用規約（必ず両方のAPIを使うこと、などのルール）を年明けくらいから制定していこうと考えているところです。
その点をご留意いただければと思います。

**Comment by Foo-x** [comment]
早速のお返事ありがとうございます。
MITライセンスとのことで承知しました。

たしかにAPIはタダ乗りされると損ですよね。
forkと機能追加はいったんAPIの規約をお待ちしてからにします。
ちなみに追加しようとしていた機能は、ほしい物リストにチェックボックスか何かを置いて、チェックされていたらセール中の作品だけにフィルタするものです。（セールされていない作品の `<li>` タグを `display: none` にするイメージ）

こちらのIssueは解決しましたのでcloseします。
